# Generated by Django 4.1.7 on 2023-03-31 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_acessorio_cor_veiculo_delete_editora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Veiculos', to='garagem.categoria'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Veiculos', to='garagem.cor'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Veiculos', to='garagem.marca'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
